// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGi4TVqIkghyYSGSPhn5Ry8kg26s0vLuc',
    appId: '1:1097346823669:web:dcfd162f6042bbcf025cbc',
    messagingSenderId: '1097346823669',
    projectId: 'chat-app-3c80e',
    authDomain: 'chat-app-3c80e.firebaseapp.com',
    storageBucket: 'chat-app-3c80e.appspot.com',
    measurementId: 'G-NXZMLDXSGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAifxNdbUq3p0tt05sx7eqMZGFCK14gCwY',
    appId: '1:1097346823669:android:752b46655c886212025cbc',
    messagingSenderId: '1097346823669',
    projectId: 'chat-app-3c80e',
    storageBucket: 'chat-app-3c80e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnFpinqYoSZ2c3hNGO8cmoftxQoTRftWk',
    appId: '1:1097346823669:ios:8a7194e1fb096e71025cbc',
    messagingSenderId: '1097346823669',
    projectId: 'chat-app-3c80e',
    storageBucket: 'chat-app-3c80e.appspot.com',
    iosClientId: '1097346823669-pv1s4011glpvqsin6bh5a8sm4ibruphl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnFpinqYoSZ2c3hNGO8cmoftxQoTRftWk',
    appId: '1:1097346823669:ios:8a7194e1fb096e71025cbc',
    messagingSenderId: '1097346823669',
    projectId: 'chat-app-3c80e',
    storageBucket: 'chat-app-3c80e.appspot.com',
    iosClientId: '1097346823669-pv1s4011glpvqsin6bh5a8sm4ibruphl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
